# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Joran

[package]
name = "rust-serial-tool"
version = "2.0.1"
edition = "2024"
license = "MIT"

[[bin]]
name = "serial-tool"
path = "src/main.rs"

[dependencies]
chrono = "0.4.45"
directories = "6.0.0"
eframe = "0.36"
egui_dock = "0.21"
encoding_rs = "0.8.35"
image = { version = "0.25", default-features = false, features = ["png"] }
rfd = "0.17.2"
serde = { version = "1.0.229", features = ["derive"] }
serialport = "4.10.0"
sys-locale = "0.3.2"
toml = "1.1.4"

[build-dependencies]
embed-resource = "3"
